{% set name = "ginga" %}
{% set version = "2.6.5" %}
{% set hash_type = "sha256" %}
{% set hash_value = "0a8000a2e872d10fd05368cf3fa9d48d67c9191877998d764cd681f3f88b0e25" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  entry_points:
    - ginga = ginga.rv.main:_main
    - ggrc = ginga.misc.grc:_main
  script: python setup.py install --offline --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - astropy >=1.0
    - numpy >=1.9
    - qtpy >=1.1
    - setuptools >=1.0
  run:
    - python
    - astropy >=1.0
    - numpy >=1.9
    - qtpy >=1.1

test:
  imports:
    - ginga
    - ginga.aggw
    - ginga.cairow
    - ginga.canvas
    - ginga.canvas.types
    - ginga.cvw
    - ginga.doc
    - ginga.fonts
    - ginga.gtk3w
    - ginga.gtk3w.plugins
    - ginga.gtkw
    - ginga.gtkw.plugins
    - ginga.gw
    - ginga.icons
    - ginga.misc
    - ginga.mockw
    - ginga.mplw
    - ginga.opencl
    - ginga.opengl
    - ginga.pilw
    - ginga.qtw
    - ginga.qtw.plugins
    - ginga.rv
    - ginga.rv.plugins
    - ginga.table
    - ginga.tkw
    - ginga.util
    - ginga.web
    - ginga.web.bokehw
    - ginga.web.pgw
  commands:
    - ginga --help
    - ggrc --help

about:
  home: http://ejeschke.github.com/ginga
  license: BSD 3-clause
  license_family: BSD
  summary: An astronomical image viewer and toolkit
  description: |
    Ginga is a toolkit designed for building viewers for scientific image
    data in Python, visualizing 2D pixel data in numpy arrays.
    The Ginga toolkit centers around an image display class which supports
    zooming and panning, color and intensity mapping, a choice of several
    automatic cut levels algorithms and canvases for plotting scalable
    geometric forms.  In addition to this widget, a general purpose
    ''reference'' FITS viewer is provided, based on a plugin framework.
    Ginga is distributed under an open-source BSD licence. Please see the
    file LICENSE.txt in the top-level directory for details.
  doc_url: http://ginga.readthedocs.io/
  dev_url: https://github.com/ejeschke/ginga

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - ejeschke
    - pbvarga1
