travis:
  secure:
    BINSTAR_TOKEN: Yde9RW1p2YLQBhIGy6ritbmqAPlUo+0fxrhISx2rQg7qOu4CuPBCAgy1jsIn8/nrmc+7LCgeMMU2glx7kJPsev1DEgH3YEeLKockrper6GeQ4ZbbKM2ah8IZ30Bb4eoSGZ6FZTiEehWZYsK/bsKVcc6D1n7th7NkzzyaoEqEFFhu1Fyxree1+RKytm0NM2+m2NyvV80vRkKHnDpbLKvXs9Aio/fqNU2w/zQ3ON4W0t3CA6h+6e+AkjUFARBJFoKBcS4pfK+ojDvQEenC80jJ7LbNkPLNr3kxaF08MpS6w+aNJ1OkyeJfkWwxJ5wThG3k6lX6uBl6dmIlF9otOX3zhg+lsl/pYchVQlGiAoLgu9goqRaMhlKXBBz3ZZqNIfR+0pSChAfbkBCl2OzZQVFHYjxTBmSCTBuikA5KZWuMp0qPk28oE3TKLCH7pQix2UmjMDAXBAwKRtyoevohvbZ8T8GGknGs95z0HeTGTcbYvUlM0zbfg8SyuG2SRgXn6aR2w96rjVOXxD526igLPkLpZ/iarRUVrm5ZTdiFWoLSbWbdoNsavNc0J4kmiDEMt+DNcNH/xr3+sQmLeU8o4Mg0PK80TpzGHYAlr32/06pZ/ZPgqhpMj8Qs9nyMqSX5to4amMovb7wQ3EmKXlAvvWd2xibJ9P9get13maLhqIlRIdc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
