travis:
  secure:
    BINSTAR_TOKEN: LX6TGwfkmFp+wftJAgMswU2lA4f5IHdDf8d7YUkCKfx/gNhSmLMt/0Zqqokf9PkkbrOymPy5Zh365g9Q6enNLreqSUsuF+8zCgmwBEtKp/kg2/wps1LfzzRRihnLkeJahUag6ywNVUBmmq/SDIGP6CjIEJbtFe7TkTqzPR7eMq5yNIkGByQr4GA+R5K9fltJDml++s4g3MaAcphGtIy5dHPpPMraQH35QMi29iC1HPFMgawHLAXHd39myZcDGiK6xtu1n2IhURkzwKCGJ6TuUyuveXL3C7xSmvSmVzbG9QZnFKBV7WI/YNAQwIS0ZPtqrCiA1UPKt0ViO20ameP0x5U6tBMJpUrpU5Tr0UtZ+aISEUSScNZrzAjlnQ2ZZoxEgU1tQe1sHcEVqaR56bdWTc3TWZlKy1qepkpZgMouF57sAbU+QDeo1pI4uMSXi8DDGY6RaawG8QE3StlkkWIz07A1vETUvehFGP9OCQEL78gZZOYAXA1dRNc29Y3uUB5osvtyl0q7ADY/BenlAyOCvsXpceBAsS8PTv1170eSRwFrLf4LNkFBlQPnpbkhz6T0DVMuJcC/U0Wos8JGV46M6XPp2ZtjCUb9C5n63TfC6LHGo2qWHRC2Iiw9ZSSwH88EbomIoC/ppf1aeqpGV8K4IqDXApRJmeJaRxlotHpOnXE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
